site_name: manual_dev

nav:
  - index.md
  - Development:
    - dev/index.md
    - Coding Guildelines: dev/coding_guidelines.md
    - Development Environment:
      - Overview: dev/development_environment.md
      - IntelliJ: dev/intellij.md
    - System Architecture:
      - Flow diagrams: 
        - Catalog: dev/flow_diagrams_catalog.md  
  - UX Guidelines:
    - ux/index.md
    - Design Pattern:
      - Overview: ux/patterns.md
      - Navigation: ux/nav.md
      - Empty state: ux/empty_state.md
      - Tooltip: ux/tooltip.md
    - Components:
      - Overview: ux/components.md
      - Alert: ux/alert.md
      - Button: ux/button.md
      - Card: ux/card.md
      - Delete object: ux/delete_object.md
      - File: ux/file.md
      - File Upload: ux/file_upload.md
      - Labels & Tags: ux/label_tag.md
      - Object integration: ux/object_integration.md
      - Object representation: ux/object_representation.md
      - Performance widget: ux/performence_widget.md
      - Pickers: ux/pickers.md
      - Scope: ux/scope.md
      - Status: ux/status.md
      - Switch & Sliders: ux/switch_slider.md
      - Tab / Tab pane: ux/tab.md
      - Table: ux/table.md
  - Manual How-To:
    - documentation/index.md
    - Setup Visual Studio Code: documentation/howto-visual-studio.md
    - Tips for authors: documentation/author-tips.md