site_name: manual_admin

nav:
  - index.md
  - Administration:
    - System: "administration/System.md"
    - Core functions:
      - Overview: "administration/Core_functions.md"
      - Landing pages: "administration/Landing_pages.md"
      - REST API: "administration/REST_API.md"
      - E-Mail Settings: "administration/E-Mail_Settings.md"
      - Files and Folders: "administration/Files_and_Folders.md"
      - WebDAV: "administration/WebDAV.md"
      - Licenses: "administration/Licenses.md"
    - Login:
      - Overview: "administration/Login.md"
      - Security: "administration/Login_Security.md"
      - Password and Authentication: "administration/Login_Password_and_Authentication.md"
      - Guest and invitation: "administration/Guest_and_invitation.md"
      - Self-registration : "administration/Login_Self-Registration.md"
    - Modules:
      - Overview: "administration/Modules.md"
      - Module Instant Messaging: "administration/Instant_Messaging.md"
      - Module Course Reminders: "administration/Modules_Course_Reminders.md"
      - Module Video: "administration/Modules_Video.md"
      - Module Audio/Video Recording: "administration/Modules_Audio_Video_Recording.md"
      - Module Contact Tracing: "administration/Modules_Contact_Tracing.md"
      - Module Document pool: "administration/Modules_Document_pool.md"
      - Module Taxonomy: "administration/Modules_Taxonomy.md"
      - Module Media Center: "administration/Modules_Media_Center.md"
      - Module Events / Absences: "administration/Modules_Events_and_Absences.md"
      - Module Course: "administration/Modules_Course.md"
      - Module Catalog: "administration/Modules_Catalog_2.0.md"
      - Module Repository: "administration/Modules_Repository.md"
      - Module Organisations: "administration/Modules_Organisations.md"
      - Module Course Planner: "administration/Modules_Course_Planner.md"
      - Module To-do: "administration/Modules_ToDo.md"
      - Module Projects: "administration/Modules_Projects.md"
      - Module Quality Management: "administration/Modules_Quality_Management.md"
      - Module OAI PMH: "administration/Modules_OAI.md"
    - Life cycles:
      - Overview : "administration/Life_cycles_-_Administration.md"
      - Automatic Group Lifecycle: "administration/Automatic_Group_Lifecycle.md"
    - Payment modules:
      - Overview: "administration/Payment_modules.md"
      - Invoice: "administration/Payment_Invoice.md"
      - PayPal Configuration: "administration/Payment_PayPal.md"
    - Reports: "administration/Reports.md"
    - e-Assessment Administration:
      - Overview: "administration/e-Assessment_Administration.md"
      - ePortfolio: "administration/eAssessment_ePortfolio.md"
      - Question bank: "administration/eAssessment_Question_bank.md"
      - Einstufung/Noten: "administration/Assessment_translate_points_in_grades_admin.md"
      - OpenBadges: "administration/e-Assessment_openBadges.md"
    - External tools :
      - Overview : "administration/External_Tools_-_Administration.md"
      - BigBlueButton module: "administration/BigBlueButton_module.md"
      - SharePoint / OneDrive: "administration/SharePoint_OneDrive.md"
      - Zoom integration: "administration/Zoom.md"
      - Analytics module: "administration/Analytics_module.md"
      - LTI 1.3 Integrations: 
        - Overview: "administration/LTI_Integrations.md"
        - External tools : "administration/LTI_External_tools.md"
        - External platforms : "administration/LTI_External_platforms.md"
        - Deep Linking : "administration/LTI_Deeplinking.md"
        
    - Customizing: "administration/Customizing.md"

  - User management:
    - usermanagement/index.md
    - User / Account Search:  "usermanagement/Search_Users.md"
    - Create User: "usermanagement/Create_User.md"
    - Assign roles: "usermanagement/Assign_roles.md"
    - Configure User: "usermanagement/Configure_User.md"
    - Delete User: "usermanagement/Delete_User.md"
    - Data protection: "usermanagement/Data_protection.md"

  - Installation:
    - Installation guide: "installation/installGuide.md"
    - Update guide: "installation/updateGuide.md"
    - Supporting tools installation:
      - imageMagick: "installation/imageMagick.md"
      - Gotenberg PDF: "installation/gotenbergPdf.md"
      - AthenaPDF: "installation/athenaPdf.md"
      - HandBrakeCLI: "installation/handBrakeCli.md"
      - ffmpeg: "installation/ffmpeg.md"
    - Alternative installation environments:
      - MySQL DB: "installation/mysql.md"
      - Windows support: "installation/windows.md"
      


      

# TODO
# - hardware requirements
# - Shibboleth
# - services: handbrake, imagemagik, athenapdf, covid-cert
# - addons: hints to bbb, onlyoffice...
